"""create follow and recorda_like tables

Revision ID: 0003_follow_and_recorda_like
Revises: 0002_diagram_schema
Create Date: 2026-09-21 00:14:41.463289

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0003_follow_and_recorda_like"
down_revision: str | None = "0002_diagram_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follow",
        sa.Column(
            "follow_id",
            sa.Uuid(),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("follower_id", sa.Uuid(), nullable=False),
        sa.Column("following_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING', 'ACCEPTED')", name="ck_follow_status"
        ),
        sa.CheckConstraint(
            "follower_id <> following_id", name="ck_follow_no_self_follow"
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"], ["app_user.user_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["following_id"], ["app_user.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("follow_id"),
        sa.UniqueConstraint(
            "follower_id", "following_id", name="uq_follow_follower_id_following_id"
        ),
    )
    op.create_index("ix_follow_follower_id", "follow", ["follower_id"], unique=False)
    op.create_table(
        "recorda_like",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("recorda_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recorda_id"], ["recorda.recorda_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "recorda_id"),
    )
    op.create_index(
        "ix_recorda_like_recorda_id", "recorda_like", ["recorda_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_recorda_like_recorda_id", table_name="recorda_like")
    op.drop_table("recorda_like")
    op.drop_index("ix_follow_follower_id", table_name="follow")
    op.drop_table("follow")
    # ### end Alembic commands ###
